### ISSUE TITLE
Profile#avatar=(avatar) Issue

### ISSUE THREAD

**Issue by rdcuzins** [meew0/discordrb#102]
Seems like from what I was seeing online and from another user, Ruby does not like how this is handled on Windows.  Or at least my version of ruby (2.2.4p230) and Windows 10. I had to use:

image = open('C:\Path\to_the\picture.jpg', 'rb')
avatar ='data:image/jpg;base64,'
avatar += Base64.strict_encode64(image.read)

botProfile.avatar=(avatar)

before I called bot.run to get my avatar to change.

**Comment by meew0** [comment]
Known issue, see https://github.com/meew0/discordrb/issues/96
