### ISSUE TITLE
Add :required_permissions attribute to CommandContainer

### ISSUE THREAD

**Issue by PoVa** [meew0/discordrb#104]
I think this would be really useful. Instead of having to do:
```ruby
extend Discordrb::Commands::CommandContainer
command(:command) do |event|
  if event.author.permission?(:manage_messages, event.channel)
    #Do stuff here
  end
end
```
we could do:
```ruby
extend Discordrb::Commands::CommandContainer
command(:command, required_permissions: [:manage_messages, :kick_members]) do |event|
  #Do stuff here
end
```

**Comment by meew0** [comment]
Yeah, this seems useful

**Comment by PoVa** [comment]
Also, adding `:no_permission_message` attribute to CommandBot, which works similar to `:command_doesnt_exist_message`, so it outputs something like `You need %permission% to use this command.` might come in handy.

**Comment by meew0** [comment]
There is already a command's `:permission_message` which I'll just reuse.
