### ISSUE TITLE
ANOTHER event.author problem

### ISSUE THREAD

**Issue by SnazzyPine25** [meew0/discordrb#106]
Pertaining to my last issue that has the same code: https://github.com/meew0/discordrb/issues/95

I got another error with my FilterEdit event container after updating to 2.0.4
```
[WARN : gateway @ 2016-04-18 13:45:07.910] Edited a message with nil author! Content: nil, channel: <Channel name=todo id=172111155450478592 topic="Planned featured and stuff. 🔴 Not done - ⚪️ In development - ⚫️ Testing phase - 🔵 Finished and available!" type=text position=8 server=#<Discordrb::Server:0x8f8c278>>
```
This error appears when a channel topic is changed.

There's also another error I encountered:
```
[WARN : gateway @ 2016-04-18 14:33:37.510] Edited a message with nil author! Content: nil, channel: <Channel name=botchat id=167106348482428928 topic="" type=text position=1 server=#<Discordrb::Server:0x9365bb0>>
```
That I probably encountered by using a certain command.
```ruby
bot.command :urban do |event, *args|
  if not event.user.id == 158049329150427136 then
  event << ":no_entry: This command is only for the developer of the bot!"
  else
    definition = UrbanDict.define(args.join(' '))
    definition
  end
end
```

**Comment by meew0** [comment]
It should no longer trigger the event, does it?

**Comment by SnazzyPine25** [comment]
It does but the error displays in a different way now. Also The second error displays randomly when a message gets edited.

**Comment by meew0** [comment]
It's not an error, it's a warning. I'm not sure what causes edited messages to have null content, so I put that warning to notify the user. I'll probably make it an info or debug message in the future
