### ISSUE TITLE
Allow usage of f.e. `!` and `@bot` as prefix

### ISSUE THREAD

**Issue by green-big-frog** [meew0/discordrb#107]
I'd like to have my bot respond to `!help` as well as `@bot help` with the same message.

**Comment by hlaaftana** [comment]
meew use regex

**Comment by meew0** [comment]
@hlaaftana https://www.youtube.com/watch?v=9Av7ocXB9H8

**Comment by hlaaftana** [comment]
are you implying you already use regex or it's hard to use regex with your current system

**Comment by SnazzyPine25** [comment]
You can use a commandbot with the prefix `!`.
For a prefix being the bots mention, Enter your bot's mention and then put `\`after that. You will get something like `@<bunchofnumbers>`
You can use as a prefix, but you also have to put a space after the mention for the bot to respond to this `@bot help`

**Comment by green-big-frog** [comment]
@SnazzyPine25 I'm talking about using **both** at the same time.

**Comment by SnazzyPine25** [comment]
Oh, yeah thats useful
