### ISSUE TITLE
Bot doesn't seem to run, but no errors

### ISSUE THREAD

**Issue by GammaCodeX** [meew0/discordrb#11]
Hey sorry about the super terrible issue description, but I really have no idea why this doesn't work. I made a new discord user for the bot logged it into a channel, changed email and password in your ping example and ran it. I get no errors or anything in stdout, so I assume the bot is running, but when I log in on my own account the user for the bot is not online, and it does not respond to the ping message. Inserting a puts statement just before and after bot.run shows that bot.run is reached and not exited which I assume is the wanted behaviour of the script... but the bot is not responding or even show as online

**Comment by meew0** [comment]
Could you set bot.debug = true and run it again, then post the output?

**Comment by GammaCodeX** [comment]
Ah good so there is a debug feature :P Added the line bot.debug = true and ran again. after a short while (about ½-1 sec) I get the line [DEBUG] Raised a Discordrb::Events::DisconnectEvent

After that silence, but as mentioned the script does not exit bot.run, nor does the bot go online

**Comment by meew0** [comment]
Is the DisconnectEvent all that gets output into the terminal or is there other messages? Also, could you post your code (censor out passwords and such)

**Comment by GammaCodeX** [comment]
yes nothing is said at least for a few minutes after the DisconnectEvent.. the code is:

    require 'discordrb'

    bot = Discordrb::Bot.new "[mailofbot]", "[botpassword]"

    bot.debug=true

    bot.message(with_text: "Ping!") do |event|
        event.respond "Pong!"
    end

    bot.run

as you can see just the ping example... now with a debug statement

**Comment by meew0** [comment]
Huh. What environment are you on (OS, ruby version etc.)?

**Comment by GammaCodeX** [comment]
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]
on ubuntu 15.04 (64 bit)

2015-10-10 11:35 GMT+02:00 meew0 <notifications@github.com>:

**Comment by meew0** [comment]
I have absolutely no idea what might be causing your issue. Try updating ruby to the latest version maybe?

**Comment by meew0** [comment]
Also, are you sure you didn't mistype the password?

**Comment by GammaCodeX** [comment]
Mistyped password correctly gave me a 400, so I'm pretty sure that wasn't my issue.. But getting ruby2.2 did work... the bot works now. Want me to close this thread? I mean the issue is not resolved per say, but you could just list ruby2.2 as a requirement and be done here :P

**Comment by meew0** [comment]
I'm gonna close this issue now; I've added some more debug stuff to the disconnect in commit da36d0d. If it happens again to somebody else this information might help.
