### ISSUE TITLE
event.bot.profile.avatar Fails with Exception: 500 Internal Server Error

### ISSUE THREAD

**Issue by z64** [meew0/discordrb#131]
Copied another users working `event.bot.profile.avatar=` code:

```ruby
require 'discordrb'

bot = Discordrb::Commands::CommandBot.new #snip

bot.ready() do |event|
    avatar = File.open('avatar.jpg', 'r')
    event.bot.profile.avatar = avatar
end

bot.message(with_text: "Ping!") do |event|

	event.respond 'Pong!'

end

bot.run
```

Fails upon load with

`[ERROR : et-1 @ 2016-06-01 12:10:38.080] Exception: 500 Internal Server Error: { "code": 0, "message": "must be string or buffer, not None"}`

One (of many) images tried: http://i.imgur.com/Ul4IisB.jpg
(If it means anything, I've used this image as a profile pic on Discord, as well as a server icon successfully) 

Ran it by `#discordrb`, but we couldn't find a solution. Image is in the same folder as the bot.

**Comment by meew0** [comment]
Can you try opening the file as `rb` instead of `r`?

**Comment by z64** [comment]
.... Bam. Alright then.
No idea how it worked for the other guy then that I c/p'd that code from. 
Rest of us were really scratching our heads.. they egged me on to submit an issue, I swear. :sweat_smile: 

Thanks meew! :+1:

**Comment by meew0** [comment]
It's no problem, this is a problem that appears to be entirely specific to Windows (because of how it handles binary files differently) and this solution isn't obvious. I should add this to the documentation.
