### ISSUE TITLE
Loss of voice states

### ISSUE THREAD

**Issue by snapcase** [meew0/discordrb#142]
After my bot has been running for a while it doesn't seem to get voice updates anymore.

Issuing the following command will return nothing
```
!eval event.server.voice_channels.map{|c| c.users.size}
```
This appears in the log:
```
[DEBUG : ct-447 @ 2016-06-16 10:48:34.493] Members for server x not chunked yet - initiating
[DEBUG : gateway @ 2016-06-16 10:48:34.840] Preserving voice state of member x while chunking
[DEBUG : gateway @ 2016-06-16 10:48:34.841] Preserving voice state of member y while chunking
[DEBUG : gateway @ 2016-06-16 10:48:34.842] Preserving voice state of member z while chunking
[DEBUG : gateway @ 2016-06-16 10:48:34.851] Processed one chunk on server x - length 25
[DEBUG : gateway @ 2016-06-16 10:48:34.852] Finished chunking server x
```

After restarting the bot and issuing another eval as the one above the bot will respond with:
```
[0, 3, 0, 0, 0, 0, 0]
```

**Comment by hlaaftana** [comment]
Weird, doesn't seem to be about voice states not updating but Server's `chunked` property being set to false later during runtime

As a temporary fix for *this* issue, maybe we could change Channel#users to use Server#online_members and Server#online_members to not care about the `chunked` property?
