### ISSUE TITLE
Commands don't work when using colons anywhere on them with advanced functionality turned on

### ISSUE THREAD

**Issue by unleashy** [meew0/discordrb#153]
Say I have a command with a symbol `:'hey:there'`, if I have advanced functionality turned on and do !hey:there the command doesn't activate.

This also applies if you have colons not on the symbol, for example if you send a message like `!eval MyModule::MyConstant` the command is ignored. Is this supposed to happen?

**Comment by meew0** [comment]
This is intentional; colons separate chain arguments from the chain itself. If you want to use a different character, you can change the `:chain_args_delim`.

**Comment by unleashy** [comment]
Ok, thanks.
