### ISSUE TITLE
Caching issues with voice channels

### ISSUE THREAD

**Issue by snapcase** [meew0/discordrb#159]
Voice channels no longer receive updates after bot has been running for a while.

The following code:
```puts event.server.voice_channels.map{|c| c.users.size}.inspect```
will return an array with a previously known state.

Leaving/Joining voice or toggling mute has no effect.

**Comment by meew0** [comment]
Could you try the `voice_state_fix` branch? It uses an entirely new way of tracking so it should fix your problem.
