### ISSUE TITLE
Doesn't tell user to input their own account details in instructions

### ISSUE THREAD

**Issue by zik1zik** [meew0/discordrb#16]
Pretty self explanitory, read the title <3

**Comment by meew0** [comment]
I fixed that already in 4a8821e :P

**Comment by zik1zik** [comment]
No in the Code section when you first get onto the Repository

**Comment by meew0** [comment]
You mean in the "Usage" paragraph in the instructions? Or the actual example files?

**Comment by zik1zik** [comment]
Usage paragraph for those who want to start experimenting with it <3

**Comment by meew0** [comment]
Starting with d7cf13e, the bot refuses to run at all if an example email address is entered. This should fix all such problems (assuming people actually read the stdout of the bot...)
