### ISSUE TITLE
Gateway Timeout Recovery

### ISSUE THREAD

**Issue by barkerja** [meew0/discordrb#160]
I recently noticed my bot never recovered from a gateway connection timeout. Logs can be found: https://gist.github.com/barkerja/3d40ff95c39aeab3dc1c03d98ed33432

**Comment by meew0** [comment]
This looks like a network problem - your Internet connection dropped temporarily and it didn't receive any new packets (so it got stuck sending the same heartbeat), and when the gateway connection finally dropped entirely, it couldn't reconnect.

Gateway version 5 (will be included in 2.2.0) provides a mechanism to recognise connections that are dead, but this won't help in your case.
