### ISSUE TITLE
Join interrupt bug

### ISSUE THREAD

**Issue by SnazzyPine25** [meew0/discordrb#167]
![image](https://cloud.githubusercontent.com/assets/7025343/16542103/925278bc-4036-11e6-85ab-c5bb982d80aa.png)

**Comment by meew0** [comment]
That means you pressed Ctrl+C, for example, to end the process.

**Comment by SnazzyPine25** [comment]
I didn't do that

**Comment by meew0** [comment]
Then something else must have sent `SIGINT`. http://ruby-doc.org/core-2.3.1/Interrupt.html

**Comment by SnazzyPine25** [comment]
Well could not find the soice of error.
