### ISSUE TITLE
Log-to-File Support

### ISSUE THREAD

**Issue by megumisonoda** [meew0/discordrb#171]
Requesting support for Discordrb's built-in exception and info logging to have support for logging to files generally. Also requesting support for logging to stdout / file in parallel.

**Comment by VxJasonxV** [comment]
stdout: `ruby bot.rb > file.txt`
file in parallel: `ruby bot.rb |tee -a file.txt`

**Comment by megumisonoda** [comment]
While this would work, it relies on unix-isms and discordrb is meant to support all Ruby platforms, even Windows. I can write a wrapper around this for my project, but support for this built-in would still be preferable.

**Comment by VxJasonxV** [comment]
No, it's not a Linux'ism. https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/redirection.mspx

If anything, another Ruby library should handle this instead of duplicating common process functionality across multiple gems.
