### ISSUE TITLE
using a javascript token for the bot?

### ISSUE THREAD

**Issue by mindcrimes** [meew0/discordrb#173]
I tried using bot = Discordrb::user token: 'token here' but i keep getting an error that there is no module named users defined.

**Comment by meew0** [comment]
Not sure what a "javascript token" is supposed to be, but the line should be:
```rb
bot = Discordrb::Bot.new token: 'token here', application_id: 12345
```
where the token and app ID are appropriately replaced.

**Comment by greenbigfrog** [comment]
@mindcrimes did that answer your question?

**Comment by mindcrimes** [comment]
nah but i looked through the docs and found out you just need to add type: :user to the end

**Comment by greenbigfrog** [comment]
If this is answered you might wanna close this issue.
