### ISSUE TITLE
required_permissions doesn't appear to work

### ISSUE THREAD

**Issue by z64** [meew0/discordrb#179]
![image](https://cloud.githubusercontent.com/assets/6119032/17538294/1963cb04-5e72-11e6-97e6-1bde6a6bd7a5.png)

![image](https://cloud.githubusercontent.com/assets/6119032/17538310/33bf598c-5e72-11e6-82a3-d3240fbeb7b1.png)

![image](https://cloud.githubusercontent.com/assets/6119032/17538364/8dddb328-5e72-11e6-9d3c-d9a903d3904d.png)

This first time he runs `*rename` he does not have permission.

The second time I adjusted one of his roles to include `:manage_roles` as shown

Still returns the no permission canned response.

I then run a check with `can_manage_roles?` with the permission still on, and it returns `false`

Here's the command header

```ruby
command(:rename,
        required_permissions: [:manage_roles],
        min_args: 2,
        description: "Updates a CMDR's in-game name.",
        usage: "rename @user [new name]"
) do |event, user, *name|
```

**Comment by SnazzyPine25** [comment]
The library caches objects such as servers, and with servers cached, roles are too.

**Comment by z64** [comment]
I've left `manage_roles` on that role since I've made this issue, and restarted the bot many times since. It it is still reporting `false` for `#can_manage_roles?`.

**Comment by meew0** [comment]
This particular problem is likely related to `:manage_roles` not corresponding to the actual Manage Roles permission, but instead to Administrator. (Thanks @megumisonoda for figuring this out, see also #180) Could you try a different permission and see whether it works with that?

**Comment by meew0** [comment]
Did you ever revisit this?

**Comment by z64** [comment]
Tried a few of the `#can_xyz?` calls, everything else seems in check with `eval`.. haven't tried it with specifying something else in `required_permissions:` though.

**Comment by meew0** [comment]
I'd appreciate if you did and reported back

**Comment by megumisonoda** [comment]
#180 was merged into master, so you should test this again to see if it works, @z64

**Comment by z64** [comment]
Everything appears to be working correctly now. Sorry for the delay! :heart: 

Thanks guys
