### ISSUE TITLE
`send_file` doesn't send anything

### ISSUE THREAD

**Issue by ReiFan49** [meew0/discordrb#184]
Well, after checked the way `rest-client` works,
`send_file` always return JSON error 50006 as there's nothing to send.

After checked the API side, `send_file` doesn't perform send `multipart` header on the payload. Because of that, the message processed normally without file consent or something.

(ps: did you forget to specify send_file requires file IO and possible to send multiple files?)

```Ruby
request(
  :send_file,
  :post,
  "#{api_base}/channels/#{e.channel.id}/messages", # yeah, ignore this.
  {
    content: "There you go %s" % (e.user.mention),
    file: fio, # this one is IO (need to be specified)
    multipart: true # this field is required to send a file, especially the API documentation says it
  },
  Authorization: @bot.token,
)
```

**Comment by z64** [comment]
sorry, are you saying `send_file` doesn't work?

i don't think the current method takes an array for sending multiple things.

![image](https://cloud.githubusercontent.com/assets/6119032/17798964/618399bc-65a4-11e6-9685-cd8851ecf495.png)

**Comment by unleashy** [comment]
Yeah send_file works fine on my end.

**Comment by greenbigfrog** [comment]
For me it looks like @ReiFan49 is trying to do his own request?

**Comment by SnazzyPine25** [comment]
@ReiFan49 There is no need to use requesting.
```ruby
e.channel.send_file(fio, caption: "There you go %s" % (e.user.mention))
```

**Comment by ReiFan49** [comment]
umm i think the problem is either IO or not, after retried (and re-read this) again it works. (close it?)
as the send_file if it was given file of non IO based it won't send

`[ERROR : ct-2 @ 2016-08-19 19:50:55.723] Exception: #<RestClient::BadRequest: 400 Bad Request>` shows if `send_file` performed badly like `First time` section

### First time
```Ruby
fn = 'data/img/gacha-%08x.png' % [Time.now.hash]
fio = File.open(fn,'rb')
e.channel.send_file(fn)
```
```Ruby
fn = 'data/img/gacha-%08x.png' % [Time.now.hash]
e.channel.send_file(File.read(fn))
```
vs
### Now
```Ruby
fn = 'data/img/gacha-%08x.png' % [Time.now.hash]
fio = File.open(fn,'rb')
e.channel.send_file(fio)
```

**Comment by z64** [comment]
Right.

`file (File) — The file that should be sent.`

http://www.rubydoc.info/gems/discordrb/Discordrb/Bot#send_file-instance_method

It expects a `File` object. `File.read` does not return a `File` object.
