### ISSUE TITLE
disconnect from server

### ISSUE THREAD

**Issue by mackmm145** [meew0/discordrb#2]
what's the simplest way of handling disconnects and forcing the bot to reconnect? currently, when the internet drops and comes back up, the bot doesn't respond.

**Comment by mackmm145** [comment]
nevermind, i added some code to the bot to stop the event machine on disconnect, and relog in. let me know if you want me to make a pull request?

**Comment by meew0** [comment]
Sure, I'd love a pull request. Thanks!
