### ISSUE TITLE
Not neccessarily an issue

### ISSUE THREAD

**Issue by riolibrary** [meew0/discordrb#219]
I have been looking into coding a discord bot, I looked around and saw this was the only api for ruby. What version of this gem should I use for a raspberry pi? RPi runs 1.9.3 Ruby

**Comment by meew0** [comment]
Any version of this gem will not work on Ruby versions below 2.1.0; you will have to install a later version, which should be possible as well. From some googling, I found this: https://gist.github.com/blacktm/8302741 - never tried it but looks good to me.
