### ISSUE TITLE
Selfbot unable to change game if restarted before disconnected from server

### ISSUE THREAD

**Issue by Daniel-Worrall** [meew0/discordrb#222]
Reproduce steps
1. Launch bot.
2. Change game within bot.
3. Exit bot.
4. Restart bot.
5. Try to change game.

**Comment by meew0** [comment]
That stacktrace is a 401 while sending a message and has nothing to do with changing the game.

**Comment by Daniel-Worrall** [comment]
This problem might actually be from starting the bot up too quickly before exiting it as it keeps happening while testing other things (but the change game not changing error is still a thing)

**Comment by meew0** [comment]
I can't reproduce this - setting games on user bots works fine, no matter how quickly I restart it.

**Comment by Daniel-Worrall** [comment]
I did some testing on my own, and it seemed to work but just really delayed. May be something with the rate limiter but I'm really not sure if this is an issue or not anymore.
