### ISSUE TITLE
Changing the topic of a discord server is broken

### ISSUE THREAD

**Issue by mindcrimes** [meew0/discordrb#238]
attempting to change the topic of a channel using
event.channel.topic = "hello test" gives this error in my console:
#<NoMethodError: undefined method update_channel' for Discordrb::API:Module
running 3.0.1

**Comment by riolibrary** [comment]
try this:
`event.channel.topic = ("hello test")`
Sometimes computers are iffy with the parentheses

**Comment by mindcrimes** [comment]
> try this:
event.channel.topic = ("hello test")
Sometimes computers are iffy with the parentheses
gives the same error

**Comment by Daniel-Worrall** [comment]
This is a bug in the code from when the API was rewrote and it's trying to call a method that no longer exists.

**Comment by Daniel-Worrall** [comment]
> Look at the docs

For one, this is the wrong method as this is for checking the current topic `#topic`, not assigning a new one `topic=`

I would grab the proper link, but the docs aren't working for me at this time.

**Comment by riolibrary** [comment]
> I would grab the proper link, but the docs aren't working for me at this time
[Docs](http://www.rubydoc.info/github/meew0/discordrb/master/Discordrb%2FChannel%3Atopic)
