### ISSUE TITLE
PresenceEvent, event.user is doesn't contain a name on :offline event.

### ISSUE THREAD

**Issue by sarsntony** [meew0/discordrb#24]
if event.status. == :offline
    puts event.user
    puts event.user.name
    puts "#{event.user.username} is offline"
  end

This following code contains empty string for event.user.name or event.user.username

**Comment by sarsntony** [comment]
In addition, server is also empty.

**Comment by meew0** [comment]
Sorry, I didn't get around to fixing this earlier.
