### ISSUE TITLE
Please release 3.1.0 soon

### ISSUE THREAD

**Issue by evaryont** [meew0/discordrb#253]
I ask because that should include https://github.com/meew0/discordrb/pull/243. Currently, if you turn on fancy logging, the bot will not be able to connect with a fairly unhelpful error message:

```
2016-10-16 18:29:22.631 main             D WS thread created! Now waiting for confirmation that ever
ything worked
2016-10-16 18:29:22.631 websocket        D Connecting
2016-10-16 18:29:22.783 websocket        D Gateway URL: wss://gateway.discord.gg/?encoding=json&v=6
2016-10-16 18:29:22.825 websocket        D Obtained socket
2016-10-16 18:29:23.283 websocket        ✗ An error occurred in the main websocket loop!
2016-10-16 18:29:23.300 websocket        ✗ An error occurred while connecting to the websocket!
```

Editing Discord::Gateway#connect to add `require 'pp'; pp e, e.backtrace` to the rescue handler gets an actually useful backtrace:

```
#<RuntimeError: can't modify frozen String>
["/home/colin/code/ruwby/vendor/bundle/ruby/2.3.0/gems/discordrb-3.0.2/lib/discordrb/logger.rb:94:in
 `gsub!'",
 "/home/colin/code/ruwby/vendor/bundle/ruby/2.3.0/gems/discordrb-3.0.2/lib/discordrb/logger.rb:94:in
 `write'",
 "/home/colin/code/ruwby/vendor/bundle/ruby/2.3.0/gems/discordrb-3.0.2/lib/discordrb/logger.rb:47:in
 `block (2 levels) in <class:Logger>'",
 "/home/colin/code/ruwby/vendor/bundle/ruby/2.3.0/gems/discordrb-3.0.2/lib/discordrb/logger.rb:83:in
 `log_exception'",
 "/home/colin/code/ruwby/vendor/bundle/ruby/2.3.0/gems/discordrb-3.0.2/lib/discordrb/gateway.rb:544:
in `handle_error'",
 "/home/colin/code/ruwby/vendor/bundle/ruby/2.3.0/gems/discordrb-3.0.2/lib/discordrb/gateway.rb:526:
in `rescue in websocket_loop'",
 "/home/colin/code/ruwby/vendor/bundle/ruby/2.3.0/gems/discordrb-3.0.2/lib/discordrb/gateway.rb:490:
in `websocket_loop'",
 "/home/colin/code/ruwby/vendor/bundle/ruby/2.3.0/gems/discordrb-3.0.2/lib/discordrb/gateway.rb:473:
in `connect'",
 "/home/colin/code/ruwby/vendor/bundle/ruby/2.3.0/gems/discordrb-3.0.2/lib/discordrb/gateway.rb:379:
in `block in connect_loop'",
 "/home/colin/code/ruwby/vendor/bundle/ruby/2.3.0/gems/discordrb-3.0.2/lib/discordrb/gateway.rb:378:
in `loop'",
 "/home/colin/code/ruwby/vendor/bundle/ruby/2.3.0/gems/discordrb-3.0.2/lib/discordrb/gateway.rb:378:
in `connect_loop'",
 "/home/colin/code/ruwby/vendor/bundle/ruby/2.3.0/gems/discordrb-3.0.2/lib/discordrb/gateway.rb:145:
in `block in run_async'"]
```

Which gets me the line of code: `message.gsub!(@token, 'REDACTED_TOKEN') if @token`. I originally thought it was an issue of Dotenv or ENV being frozen, and so `@token` was frozen too. But that isn't the case, if I actually read the error message closely: *`message`* is frozen. Commenting out the line will let the bot connect successfully.

If I replace the line with what's in the PR, there isn't any error as well. It's because calling `frozen_string.to_s` returns an un-frozen string, avoiding this issue.

So please release a new version of discordrb that includes the bugfix. Thanks so much!

Example that replicates the issue in v3.0.2:

```ruby
require 'discordrb'
require 'dotenv'
Dotenv.load

creds = {
  token: ENV['DISCORD_BOT_TOKEN'].dup,
  client_id: ENV['DISCORD_CLIENT_ID'].to_i,
  log_mode: :debug,
  type: :bot,
  fancy_log: true
}
puts creds
puts creds[:token].frozen?

bot = Discordrb::Bot.new creds

bot.message(with_text: 'Ping!') do |event|
  event.respond 'Pong!'
end

bot.run
```

**Comment by Daniel-Worrall** [comment]
That's a very good point. If you'd like to temporarily run using latest master you can use this in your `Gemfile`

`gem 'discordrb', git: 'git://github.com/meew0/discordrb.git'`

If you would like to not have everything in master, you can specify just this version with

`gem 'discordrb', git: 'git://github.com/meew0/discordrb.git', :ref => '9a21e5e'`

I haven't actually tested using the one underneath but it should be perfectly fine. Hope this helps in the meantime

**Comment by greenbigfrog** [comment]
(In general nothing speaks against running your bots always on master,)

**Comment by meew0** [comment]
Yeah, I agree with releasing it soon, because, to quote Linus Torvalds, some [buggy crap](https://linux.slashdot.org/story/16/10/05/210227/linus-torvalds-says-buggy-crap-made-it-into-linux-48) made it into 3.0. In the meantime, just use master.
