### ISSUE TITLE
There's stuff lingering around in the commands.rb example that doesn't work for proper bot accounts

### ISSUE THREAD

**Issue by greenbigfrog** [meew0/discordrb#260]
eg. https://github.com/meew0/discordrb/blob/master/examples/commands.rb#L25-#L31

(I can PR it alter, would just like to know meew0's opinion)

**Comment by z64** [comment]
imo, should be altered to

```ruby
# Posts an invite URL to add the bot to another server
command(:invite, permission_level: 1, chain_usable: false) do
  bot.invite_url
end
```

and include an example of

```ruby
# Sets your own permission level
command(:set_permission_level, min_args: 2) do |event, level|
  bot.set_user_permission(event.user.id, 1)
end
```

**Comment by meew0** [comment]
The invite command is a good idea, but why permission_level 1? Everyone should be able to get the invite URL in my opinion. Also, such a `set_permission_level` command is likely to get copied into production bots and may thus cause security issues.

**Comment by z64** [comment]
That's fine, I agree. I just kept it to at least retain its purpose of illustrating `permission_level`, modify it however we like.
