### ISSUE TITLE
Channel data (at least position) not being updated internally

### ISSUE THREAD

**Issue by z64** [meew0/discordrb#272]
Steps to reproduce / symptoms:

1. Pick a channel, and note its position

2. Move the channel to an arbitrary other position

3. Update the channel in some manner, i.e., `!eval event.channel.name=` or `!eval event.channel.topic=`

4. Observe that the channel is now back in its original position, wherever the bot observed the channel to be when it was started.

Similarly, I can run `!eval event.channel.position`, move the channel, run it again, move it again, etc... and the number is always the same

Websocket looks OK

1. Original channel position
```
[IN : websocket @ 2016-11-15 14:25:00.279] {"t"=>"CHANNEL_UPDATE", "s"=>7, "op"=>0, "d"=>{"type"=>0, "topic"=>"meme", "position"=>6, "permission_overwrites"=>[{"type"=>"role", "id"=>"225375815087554563", "deny"=>1024, "allow"=>0}, {"type"=>"role", "id"=>"226855600586358785", "deny"=>0, "allow"=>1024}], "name"=>"meme", "last_pin_timestamp"=>"2016-11-11T18:38:46.218000+00:00", "last_message_id"=>"248090765824098306", "id"=>"246283902652645376", "guild_id"=>"225375815087554563"}}
```

2. Moving the channel

```
[IN : websocket @ 2016-11-15 14:25:34.165] {"t"=>"CHANNEL_UPDATE", "s"=>18, "op"=>0, "d"=>{"type"=>0, "topic"=>"meme", "position"=>9, "permission_overwrites"=>[{"type"=>"role", "id"=>"225375815087554563", "deny"=>1024, "allow"=>0}, {"type"=>"role", "id"=>"226855600586358785", "deny"=>0, "allow"=>1024}], "name"=>"meme", "last_pin_timestamp"=>"2016-11-11T18:38:46.218000+00:00", "last_message_id"=>"248090765824098306", "id"=>"246283902652645376", "guild_id"=>"225375815087554563"}}
```

3. Renaming the channel
```
[IN : websocket @ 2016-11-15 14:25:55.800] {"t"=>"CHANNEL_UPDATE", "s"=>22, "op"=>0, "d"=>{"type"=>0, "topic"=>"meme", "position"=>6, "permission_overwrites"=>[{"type"=>"role", "id"=>"225375815087554563", "deny"=>1024, "allow"=>0}, {"type"=>"role", "id"=>"226855600586358785", "deny"=>0, "allow"=>1024}], "name"=>"lolwat", "last_pin_timestamp"=>"2016-11-11T18:38:46.218000+00:00", "last_message_id"=>"248091215206023168", "id"=>"246283902652645376", "guild_id"=>"225375815087554563"}}
```

It's back to position 6, so they must have got that from us.

Reproduced by @greenbigfrog

**Comment by greenbigfrog** [comment]
Issue starts [here](https://github.com/meew0/discordrb/blob/master/lib/discordrb/data.rb#L1233-L1240) in `update_from(channel`. which gets used [here](https://github.com/meew0/discordrb/blob/master/lib/discordrb/bot.rb#L701-L707) and then the final call [here](https://github.com/meew0/discordrb/blob/master/lib/discordrb/bot.rb#L1020-L1021).
@meew0 is there any reason why the position is being dropped?
