### ISSUE TITLE
Enhancement - Display commands in help list based on permission

### ISSUE THREAD

**Issue by FormalHellhound** [meew0/discordrb#273]
I think the help command could be improved if it listed commands that only the user executing the command has access to. For example if you have a command like !clear that purges the last x messages from the channel, and only people with the role "Admin" or users whose permission level allows them to run the !clear command are able to see it in their help lists, but when a regular user executes the !help command they would not see it.

**Comment by greenbigfrog** [comment]
I think meew0 isn't gonna add anything like this to the current commandbot... he plans on rewriting it sometime soon and then stuff like this might be added

**Comment by FormalHellhound** [comment]
Well either way, my suggestion is here. I know the command container takes a permission_level argument and a required_roles argument, so I wouldn't think it would be extremely difficult to implement. I just don't think I am familiar enough with the discordrb source to implement it myself, although I will likely attempt to figure it out.

Either way I think this would be a good improvement even if it only comes with the rewrite, as it will make things less confusing for regular users who don't have access to certain commands.

Thank you all for your hard work on discordrb!

**Comment by meew0** [comment]
#275 merged, thanks!
