### ISSUE TITLE
Update :administrator to :administrate in Permission flags

### ISSUE THREAD

**Issue by VxJasonxV** [meew0/discordrb#279]
Every Permissions flag is a verb, except for :administrator. We already have a method alias for `can_administrate`, but the verb should be the primary form for consistency in symbols as well. I would like to see `:administrate` and `can_administrate` be the primary symbol/method, `:administrator` and `can_administrator` become the alias, to be dropped in a future release (3.3?).

Can a 'usage warning' be applied to both? I believe instead of using `alias_method`, you can create a method that drops a warning message into stdout and then allow it to work as an alias, but I'm unsure if something like that can be done as easily for symbol usage.

**Comment by meew0** [comment]
The fact that everything but `administrator` is a verb is consistent with the [official docs](https://discordapp.com/developers/docs/topics/permissions) as well as Discord's permission GUIs. While discordrb's `Flags` hash is not necessarily consistent with either, it would be a pretty big change to differ here. I'm fine with an alias but I don't think actually changing the name is a good idea.

**Comment by z64** [comment]
After being schooled a bit, I'm finishing the specs for #322 I'll add this alias before I merge it.
