### ISSUE TITLE
Emoji list doesn't update

### ISSUE THREAD

**Issue by Daniel-Worrall** [meew0/discordrb#284]
If an emoji is added to a server after the bot is launched, it doesn't show up on the server emoji list using `Server#emoji`

**Comment by z64** [comment]
Just to give some more detail on this:

Discordrb doesn't currently support `GUILD_EMOJIS_UPDATE`

`[DEBUG : websocket @ 2016-12-06 21:04:29.657] Event GUILD_EMOJIS_UPDATE has been received but is unsupported, ignoring`

**Comment by meew0** [comment]
This is a caching issue as the emoji are cached once when requesting them and the cache will never be invalidated. As @z64 said this can only really be fixed by implementing `GUILD_EMOJIS_UPDATE` which shouldn't be too hard - I'll look into it once I have time
