### ISSUE TITLE
Add UnknownEvent Event

### ISSUE THREAD

**Issue by LikeLakers2** [meew0/discordrb#288]
Relevant line of code: https://github.com/meew0/discordrb/blob/master/lib/discordrb/bot.rb#L1109

So over in the code that handles raising all the events, we find that any unknown events sent from Discord are simply ignored by Discordrb itself. I propose that unknown events raise an UnknownEvent event, with one of the hashes of this new event being the hash (or JSON) data for this event.

This should allow for developers to receive events for things like CHANNEL_PINS_UPDATE or anything else that might be otherwise unsupported by Discordrb at that moment, and parse them as they desire, without having to hack into discordrb's code or wait for it to be added to the code here on Github.

**Comment by greenbigfrog** [comment]
Nice idea! But it really isn't harder to add it to discordrb then to parse them yourself.

(maybe @meew0 should add a wiki page though. he just has been very busy IRL AFAIK lately)

**Comment by LikeLakers2** [comment]
I do agree, it isn't harder to add it to discordrb. But I also feel it's a good idea for those who are unwilling to contribute (such as myself -- personally I don't have the confidence but that's just me), or if discordrb ever ends up abandoned (which, while unlikely unless discord itself ends, could also include times where it's unlikely to be updated for months on end).
