### ISSUE TITLE
Message#author should be a User object if Member object cannot be found

### ISSUE THREAD

**Issue by LikeLakers2** [meew0/discordrb#290]
Relevant line of code: https://github.com/meew0/discordrb/blob/master/lib/discordrb/data.rb#L1711

Title basically says it all. I had to do this for archiving because some users had left the server, luckily the Discord API _does_ return at least _some_ information if you request a user that you do not share a server with.

P.S. If anyone really needs it, I fixed my issue by adding this line of code just below the one linked above:
```ruby
member = @bot.user(data['author']['id'].to_i) unless member```

**Comment by z64** [comment]
> the Discord API does return at least some information if you request a user that you do not share a server with.

But, the code you linked is from the `Message` class. How else would you get a message from a `User` you don't share a server with? If it is a DM, then the first case follows through and you get a `Recipient` instead (`elsif @channel.private?`).

Could you please go into more detail about what issue this "solves"?

**Comment by LikeLakers2** [comment]
I do apologize if I confused you, I meant a command for archiving a channel -- grabbing the last X messages and throwing them into a file.

Onto how I am getting messages with a User I don't share a server with. One of this command's features, which is admin only, is to grab the _entire_ history of a channel and dump it to a file. This means it can (and potentially will, especially with channels that have been running for a long time) get messages from `Channel#history` that may have `#author` as nil -- this is because Discordrb is only checking for that member's ID within that server's _current_ member list.

Does this make more sense? If not, I can try to explain a bit more (or come onto the Discord API server and attempt to explain there).

**Comment by z64** [comment]
Okay, that's fine, thanks. 

You should join up with us there. Keeps the issues on-point to discuss questions about the issue there.

Anyways, that makes sense. Not sure if the fix is the right one, stylistically, but that can be looked into
