### ISSUE TITLE
Support for Command any_roles

### ISSUE THREAD

**Issue by Daniel-Worrall** [meew0/discordrb#291]
Posting this here primarily as a stub for discussion. This was discussed as a requested feature for Commands in the Discord API server.

The attribute `required_roles` is set up as #all? so a user would need all roles. Proposed new `any_roles` attribute is for the user to only need one of the many roles to be allowed to use the command.

My personally proposed solution would be a hybrid of the two attributes with possibly Array of Arrays.
For example, [[role_1], [role_2, role_3]] would deny the user access to the command unless they had role_1 or both role_2 and role_3 (Or all 3, but that's irrelevant).

Note: This was requested by a different user, not myself.

**Comment by meew0** [comment]
Given my previous statements on further complicating handling in `execute_command`, I will put this on hold and close it. This can be revisited once there is a new system in place than one master method that does everything.

Regardless of that, I don't think it's even a good idea to put this kind of very specific checks in place - you can just as well use if statements and `role?`.

**Comment by KristupasSavickas** [comment]
Any idea on what's the new design pattern going to look like for commands?
