### ISSUE TITLE
Don't split quoted command arguments by newline

### ISSUE THREAD

**Issue by LikeLakers2** [meew0/discordrb#296]
Relevant method: https://github.com/meew0/discordrb/blob/master/lib/discordrb/commands/parser.rb#L121

Title, as per usual. The command chain parser splits by spaces, and due to its method of doing so, also splits by newlines... which is usually fine, except it also splits anything that's quoted too, which means quotes with newlines are multiple arguments. So my suggestion is to just treat it like we do the space when quoted -- that is, we temporarily turn any instance of `\n` within a quote into a hacky_newline, then back into `\n` later.

This one was a bit weird for me to figure out my own personal fix for, but that's how I fixed it -- adding a `hacky_newline` variable assigned to a packed `0xe004`, adding a rule (or whatever you wanna call it) for `\n` to change them to `hacky_newline` but only when they're quoted, and then later gsubbing `hacky_newline` back to `\n`.

**Comment by LikeLakers2** [comment]
Hey there, I just noticed that the code used to replace hacky_newlines with actual newlines now causes the hacky_space stuff to not work -- someone forgot that `.gsub` works on a copy, not modifying the original. If you want to modify the original, you use `.gsub!`.

Have fun.

**Comment by meew0** [comment]
Fixed in e7d1e3c
