### ISSUE TITLE
Add an error handler attribute to CommandBot

### ISSUE THREAD

**Issue by LikeLakers2** [meew0/discordrb#299]
This is just an idea I had floating within my head the past couple days. The idea is that, when you're using a CommandBot, you're working with potentially a few thousand lines of code, any bit of which could error out, often causing the bot to mysteriously not respond to a certain event when it should.

What I would like to suggest is a new attribute for CommandBot (could perhaps be included in Bot, but it'll probably get more use with CommandBot) that would be set to a Proc that will be run in the case of a command erroring out for whatever reason when not within a `begin/rescue/end` block, being given the exception details and perhaps the Event too.

Now ideally, bot devs wouldn't have the errors in the first place, however this would be useful as the bot dev would be able to send a new message at least notifying the user that an error occured, without having a `begin/rescue/end` block in every command their bot has, instead of leaving the user hanging and just wondering "what do".

**Comment by greenbigfrog** [comment]
I also could imagine sth like getting a SMS when a error occurs etc. (The SMS part would only make sense if there would error checking beforehand)

**Comment by meew0** [comment]
I can see how this would be useful, but at the current stage I don't want to make `CommandBot` any more convoluted than it is already. It will probably come in a future version where I fix it all up.

**Comment by Gaelan** [comment]
@greenbigfrog Why SMS? We're literally writing a bot for a communication platform. Send a Discord PM!

**Comment by LikeLakers2** [comment]
@Gaelan I think what greenbigfrog is thinking of, is if you're often out and about and prefer to (or cannot) have Discord *not* running in the background of their phones. Or in cases such as large bots, or when you're expecting to have an error replicated but can't be watching the bot console all the time. There are many factors, and I consider his solution to have the same reasoning as statuspage.io having SMS alerts at a certain pricing point.

**Comment by LikeLakers2** [comment]
Added in #360, closing this issue by request from z64.
