### ISSUE TITLE
Internal handlers for MESSAGE_REACTION_ events

### ISSUE THREAD

**Issue by LikeLakers2** [meew0/discordrb#300]
While the internal handlers are just that, *internal* handlers, I believe that [this](https://github.com/meew0/discordrb/blob/master/lib/discordrb/bot.rb#L988-L1002) section of code (which is the `#handle_dispatch` code for MESSAGE_REACTION_ events) should be changed to have calls to internal handlers. I am suggesting this because things like CREATE_MESSAGE, which also do *not* have caching, still have [their own internal handlers](https://github.com/meew0/discordrb/blob/master/lib/discordrb/bot.rb#L817-L833), which I'm lead to believe are there for purposes of being overwritten by code supplied by the user -- and indeed, that seems to be their purpose, to be overwritten, as [a comment under the MESSAGE_CREATE event](https://github.com/meew0/discordrb/blob/master/lib/discordrb/bot.rb#L926-L929) leads me to believe.

Since we're talking about the [`Bot#handle_dispatch` method](https://github.com/meew0/discordrb/blob/master/lib/discordrb/bot.rb#L851-L1141), I might as well also suggest that an internal handler method also be added for [MESSAGE_DELETE_BULK](https://github.com/meew0/discordrb/blob/master/lib/discordrb/bot.rb#L963-L978), although whether this would be useful or not is really up to the end user, which I believe is the point of the blank internal handler methods mentioned above.

**Comment by meew0** [comment]
`MESSAGE_CREATE` has an internal handler specifically because of `CommandBot`, so it doesn't have to define event handlers there. You're right in that it could be useful for reaction events too, I'll look into it later
