### ISSUE TITLE
Passing http://anything to Command displays command_doesnt_exist_message.

### ISSUE THREAD

**Issue by munirehmad** [meew0/discordrb#319]
```
command_bot.command(:abc) do |e|
  'test'
end
```

bot initialized with
`command_doesnt_exist_message: 'Not found'`

then when I do

`!abc http://abc`

Bot says 'Not found' in text channel

`!abc hello`

Runs just fine. and bot says 'test' in channel

**Comment by meew0** [comment]
Are you using `advanced_functionality`?

**Comment by meew0** [comment]
Resolved on Discord (disable `advanced_functionality` or change `chain_args_delim`)

**Comment by munirehmad** [comment]
Resolved. Thank you.
