### ISSUE TITLE
[CommandBot] Don't respond with return value if messages have been sent

### ISSUE THREAD

**Issue by Gaelan** [meew0/discordrb#324]
Seems pretty unlikely that someone will use `event.respond`/`event<<`/`event.channel.send_embed` and also return a value, so it's probably a good idea to ignore return value (maybe with a warning) in this case. You could probably also ignore return values if they `to_s` to the `#<Foo>` notation.

**Comment by z64** [comment]
I do this.

**Comment by Gaelan** [comment]
Fair point. In "load remote data/slow computation" cases you could use the typing indicator instead, but there are probably other use cases. The `#<>` detection (or even just detection of Discordrb classes) still seems like a good idea though. Maybe we could fully drop returns (seems like more trouble than it's worth to me) in the next major.

**Comment by z64** [comment]
I wasn't very clear when I said "some long process"

Imagine perhaps 30 seconds, to several minutes. Typing indicator doesn't really get the point across, as I'm not going to block or thread to keep it going that long.

Fully dropping implicit returns to Discord won't happen. That's a feature that allows very simplistic commands.

```ruby
bot.command(:moo) { 'cow' }
```

Detection of classes I don't think is desirable either ; this would complicate simple debugging commands like `eval` I believe that might inherently return Discordrb objects to be inspected from within Discord.

Implicit returning is a feature people who know Ruby already should be familiar with ; as its a feature of Ruby, it's mirrored (abstractly) in the lib and thereby also already familiar - and by that passing `nil` at the end of a command block isn't a big enough deal to change anything.

@meew0 's call, but that's just my two cents.

**Comment by meew0** [comment]
I don't think this is a good idea; the most important sources of accidental messages are already covered (`event << 'string'` returns `nil`, and `Message` objects from `event.respond` etc. calls are ignored). To me, it doesn't seem like there are many cases where some kind of response call wouldn't be the last thing in a block anyway, so I would think it causes more confusion than it solves problems.

Ignoring return values by detecting the `#<>` format specifically also seems like a bad idea: what if the bot legitimately wants to send a string like that (or an object that stringifies to it)? I often encounter strings like that when debugging, and I can imagine others do too. Also, not all `inspect` methods are defined like that (discordrb's aren't, for example)

**Comment by greenbigfrog** [comment]
I think the strongest point against this is (as @z64 pointed out) that implicit returns is a ruby feature (which I personally like).
Even changing this on a major would force everyone to rewrite their bot. Maybe someone wants to create a parallel drb version which doesn't have the implicit returning `¯\_(ツ)_/¯`

**Comment by grioja** [comment]
Just wrote a new bot and didn't even realize this was a thing... I assumed you would just have us call `event.respond` or something. Was the cause of much wasted debugging to find out the return value was to be sent to the channel as well. I just have a nil at the end of the block now.

**Comment by z64** [comment]
For future reference, it's covered in the Wiki. https://github.com/meew0/discordrb/wiki/Commands#defining-commands

**Comment by meew0** [comment]
Everything has been said here really; right now I think the benefits of this feature outweigh their drawbacks. I'll consider it in case of a future major overhaul to the command system though.
