### ISSUE TITLE
Server.member_count can be nil

### ISSUE THREAD

**Issue by Roughsketch** [meew0/discordrb#327]
After leaving my bot running overnight, I noticed a large block of exceptions having to deal with adding and deleting members. I believe what is happening is that on Server initialization, `data['member_count']` is undefined. 

Relevant line: https://github.com/meew0/discordrb/blob/master/lib/discordrb/data.rb#L2250

Here are the exceptions:

```
[ERROR : websocket @ 2017-02-20 13:02:48.283] Exception: #<NoMethodError: undefined method `+' for nil:NilClass>
[ERROR : websocket @ 2017-02-20 13:02:48.289] /home/tewi/.rvm/gems/ruby-2.3.0/gems/discordrb-3.2.0.1/lib/discordrb/data.rb:2416:in `add_member'

...

[ERROR : websocket @ 2017-02-20 13:04:29.254] Exception: #<NoMethodError: undefined method `-' for nil:NilClass>
[ERROR : websocket @ 2017-02-20 13:04:29.259] /home/tewi/.rvm/gems/ruby-2.3.0/gems/discordrb-3.2.0.1/lib/discordrb/data.rb:2424:in `delete_member'
```

**Comment by meew0** [comment]
Is this on a user bot?

**Comment by Roughsketch** [comment]
No this is on a regular bot. This nil object issue has been popping up in several places as well. Ever since I made my bot public I've been waking up to different nil errors. Some other places are in:

#### delete_role
```
[ERROR : websocket @ 2017-02-26 16:24:23.693] Exception: #<NoMethodError: undefined method `id' for nil:NilClass>
[ERROR : websocket @ 2017-02-26 16:24:23.694] /home/tewi/.rvm/gems/ruby-2.3.0/gems/discordrb-3.2.0.1/lib/discordrb/data.rb:2402:in `block (2 levels) in delete_role'
```

#### update_presence
(No trace, but it threw on line 647 after taking the `member_is_new = true` path I believe.)
https://github.com/meew0/discordrb/blob/master/lib/discordrb/bot.rb#L647

I think there were at least a couple more, but I can only confidently bring up ones in my console right now and ones I talked about on the discord channel.

**Comment by meew0** [comment]
If these errors are still occurring, could you enable debug mode and give me a log when they happen? This seems like it could be a problem with Discord sending invalid data.

**Comment by Roughsketch** [comment]
I just looked back as far as I could in my logs (roughly 2 days), and I didn't notice any of the above errors. If it was Discord sending bad data then it seems to be fixed now as far as I can tell.

**Comment by meew0** [comment]
I'll close this issue then, if it happens again tell me
