### ISSUE TITLE
Error when starting a rb application in cmd

### ISSUE THREAD

**Issue by vlcekmat** [meew0/discordrb#336]
When I start a bot in cmd (ruby picka.rb) it puts ERROR:

[ERROR : websocket @ 2017-04-28 10:25:41.938] The websocket connection has closed: nil
[ERROR : websocket @ 2017-04-28 10:25:41.939] Websocket close frame received!
[ERROR : websocket @ 2017-04-28 10:25:41.939] Code: 4004
[ERROR : websocket @ 2017-04-28 10:25:41.939] Message: Authentication failed.
[ERROR : websocket @ 2017-04-28 10:25:43.844] The websocket connection has closed: nil
[ERROR : websocket @ 2017-04-28 10:25:43.845] Websocket close frame received!
[ERROR : websocket @ 2017-04-28 10:25:43.845] Code: 4004
[ERROR : websocket @ 2017-04-28 10:25:43.845] Message: Authentication failed.
[ERROR : websocket @ 2017-04-28 10:25:46.066] The websocket connection has closed: nil
[ERROR : websocket @ 2017-04-28 10:25:46.067] Websocket close frame received!
[ERROR : websocket @ 2017-04-28 10:25:46.068] Code: 4004
[ERROR : websocket @ 2017-04-28 10:25:46.068] Message: Authentication failed.
[ERROR : websocket @ 2017-04-28 10:25:48.986] The websocket connection has closed: nil
[ERROR : websocket @ 2017-04-28 10:25:48.986] Websocket close frame received!
[ERROR : websocket @ 2017-04-28 10:25:48.987] Code: 4004
[ERROR : websocket @ 2017-04-28 10:25:48.987] Message: Authentication failed.
[ERROR : websocket @ 2017-04-28 10:25:53.004] The websocket connection has closed: nil
[ERROR : websocket @ 2017-04-28 10:25:53.005] Websocket close frame received!
[ERROR : websocket @ 2017-04-28 10:25:53.006] Code: 4004
[ERROR : websocket @ 2017-04-28 10:25:53.006] Message: Authentication failed.
[ERROR : websocket @ 2017-04-28 10:25:58.737] The websocket connection has closed: nil
[ERROR : websocket @ 2017-04-28 10:25:58.738] Websocket close frame received!
[ERROR : websocket @ 2017-04-28 10:25:58.739] Code: 4004
[ERROR : websocket @ 2017-04-28 10:25:58.739] Message: Authentication failed.
[ERROR : websocket @ 2017-04-28 10:26:06.958] The websocket connection has closed: nil
[ERROR : websocket @ 2017-04-28 10:26:06.958] Websocket close frame received!
[ERROR : websocket @ 2017-04-28 10:26:06.959] Code: 4004
[ERROR : websocket @ 2017-04-28 10:26:06.960] Message: Authentication failed.

**Comment by z64** [comment]
Your token is more than likely incorrect, as the message says:
```
[ERROR : websocket @ 2017-04-28 10:26:06.959] Code: 4004
[ERROR : websocket @ 2017-04-28 10:26:06.960] Message: Authentication failed.
```
The token is the only authentication credential.

Please double check you have copied it right & are implementing it in your app correctly.

**Comment by vlcekmat** [comment]
Oh yes, it was incorrect, but after I fixed it, it says that again:

[ERROR : websocket @ 2017-04-28 11:25:24.807] The websocket connection has closed: nil
[ERROR : websocket @ 2017-04-28 11:25:24.808] Websocket close frame received!
[ERROR : websocket @ 2017-04-28 11:25:24.808] Code: 4004
[ERROR : websocket @ 2017-04-28 11:25:24.808] Message: Authentication failed.
[ERROR : websocket @ 2017-04-28 11:25:26.426] The websocket connection has closed: nil
[ERROR : websocket @ 2017-04-28 11:25:26.426] Websocket close frame received!
[ERROR : websocket @ 2017-04-28 11:25:26.427] Code: 4004
[ERROR : websocket @ 2017-04-28 11:25:26.427] Message: Authentication failed.

**Comment by z64** [comment]
Sorry, but this is the only case that Discord would reply with that close code.

We may be able to help further if:
- Confirm that you're using a bot account or user account token (and also didn't use something like the app's Secret by accident)
- If you could share the code showing how you are initializing your bot, we might see another issue. (i.e., do you load the token from a file? or is it just a String literal in your script?)
