### ISSUE TITLE
Reload the bot automatically on file change?

### ISSUE THREAD

**Issue by tom-sherman** [meew0/discordrb#347]
Is this possible? Would be great for rapid development

**Comment by z64** [comment]
It is of course possible to reload a file with ruby's `load` method. However, if you're using your own `EventContainer` or `CommandContainer`, you will have to take steps to load the updated handlers into your bot's own event / command container.

You could have something that wraps the above triggered by a `guard` script.

If you'd like more help with this, discussion is better suited to our dedicated channel on the [Discord API server](https://discord.gg/discord-api).

**Comment by tom-sherman** [comment]
@z64 Nice info, thanks. Do you think auto reload is out of scope of this project and should be implemented by the end user then?

**Comment by z64** [comment]
Personally, yes. There would be many subjective ways to handle this based on how one structures their bot, and the library shouldn't have someone conform to one format for something like reloading to work. 

This is something I've been planning to add stock to my [modular bot template](https://github.com/z64/gemstone) for discordrb, maybe via implementing something like [guard](https://github.com/guard/guard) that I mentioner before to accomplish this.

**Comment by meew0** [comment]
As @z64 said, integrating this is currently outside the scope of the library, given how: it's fairly easy to implement it yourself in your own bot, but implementing it in the lib would make it have to make lots of assumptions about bot structure which I'd rather not want.

**Comment by localhostdotdev** [comment]
You can use `rerun`, e.g. `rerun ruby bot.rb` works (writing this for future Googlers)
