### ISSUE TITLE
Add additional information when encountering errors, don't use exception flows

### ISSUE THREAD

**Issue by csuhta** [meew0/discordrb#373]
When the bot receives an error from Discord, the resulting internal stacktrace is not very helpful. It's more useful to see what the bot tried to do via the API and display that along with the stack. 

This is what I've been doing as a quick fix currently, but it's not awesome:

```ruby
# Patch the gem so that errors produce way more debugging information
module Discordrb::API
  def self.raw_request(type, attributes)
    RestClient.send(type, *attributes)
  rescue RestClient::BadGateway => error
    puts "Bot received an error 502 from Discord, retrying…"
    retry
  rescue RestClient::BadRequest => error
    puts "Bot received an error 400 from Discord"
    puts "Type: #{type}"
    puts "Attributes: #{attributes}"
    puts "Response Body: #{error.response.body}"
    raise error
  rescue RestClient::Forbidden => error
    if attributes.first.to_s.include?("/v6/channels/")
      puts "Attempted to list a hidden channel, ignoring"
      return error.response # Swallow the exception
    else
      puts "Bot received an error 403 from Discord"
      puts "Type: #{type}"
      puts "Attributes: #{attributes}"
      puts "Response Body: #{error.response.body}"
      raise error
    end
  end
end
```

RestClient supports a [block-style syntax](https://github.com/rest-client/rest-client#response-callbacks-error-handling) for methods which lets you inspect all parts of the process and doesn't raise exceptions on error codes. This way you can log errors more clearly and determine if you actually need to "crash" the bot instead of continuing to process other requests.

**Comment by z64** [comment]
Hi there, thanks for opening an issue!

I think it's relevant to point out that Discord is greatly changing the way it replies with errors in API v7 (currently the library supports v6). In the future we will be able to display these *much* more helpful error messages.

Here is an example that I happened to have handy from a malformed HTTP request:
```json
{
    "code": 50035,
    "errors": {
        "guild_id": {
            "_errors": [
                {
                    "code": "NUMBER_TYPE_COERCE",
                    "message": "Value \"@me\" is not snowflake."
                }
            ]
        }
    },
    "message": "Invalid Form Body"
}
```
At the moment you only get `code` and an array of strings for errors that are sometimes not very helpful on their own.

We could probably take the time to refactor a bit of the API to more cleanly `rescue` and display these new v7 errors as you've described (or similar) when we get around to implementing them.

**Comment by z64** [comment]
This will be covered by #516. Thanks for taking the time to open!
