### ISSUE TITLE
Discord API deprecation notice

### ISSUE THREAD

**Issue by evaryont** [meew0/discordrb#381]
Recently got this email:

> This email is to let you know about some changes to our APIs. Specifically, we have released documentation on API and Gateway v6 and have deprecated all older versions (3, 4, and 5). These older versions will be discontinued on October 16, 2017.
>
> With this date, the default API version will be changing from v3 to v6. We have also recently documented our API versioning, so we recommend you start specifying a version in API requests to prevent future updates from breaking your application.
>
> To ensure your application is up to date, please check out our change log to see a list of breaking changes to our APIs. Most third-party Discord libraries are already on v6, so make sure you upgrade to the latest version available if you use one.
>
> Stay awesome!
>
> — Discord Dev Team

This issue is a confirmation of which API version discordrb implements.

**Comment by z64** [comment]
Discordrb supports API v6.

https://github.com/meew0/discordrb/blob/master/lib/discordrb/api.rb#L12

**Comment by evaryont** [comment]
Sweet, thanks for answering!
