### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by bacancy-rajnik** [meew0/discordrb#383]
Discordrb::API::User.servers(token)
Discordrb::API::User.profile(token)

Above Always give me 401

**Comment by z64** [comment]
Hi there!

A 401 on these endpoints means you are providing an incorrect token.

Note that if you are using these endpoints, be sure that you are including the appropriate token prefix, such as `Bot AbcDef`.

I saw in the chat you were using OAuth2. In your case you would prefix the token with the literal text "`Bearer`".

If you have further questions, please provide more details. If not, please close this issue if this is resolved.

**Comment by z64** [comment]
"Incorrect token" is pretty much the only answer to this problem as you've stated it without more details. If you have further issues, preferably ask about them in the discord channel and we'll do our best to resolve them.
