### ISSUE TITLE
Seeking more information about a warning message

### ISSUE THREAD

**Issue by jmfgdev** [meew0/discordrb#398]
I'd like some more information about this error message:

Received op 9 without a running session! Not invalidating, we *should* be fine though.

I haven't been able to find more info about this error, could someone give an idea what it means?

**Comment by meew0** [comment]
Discord sends a packet with opcode 9 (`INVALID_SESSION`) whenever the currently running session should be considered invalid, which can happen for a variety of reasons. The client can then respond by starting a new session. It makes no sense to receive this packet when no session is currently running, so something must have gone wrong either on Discord's side or on discordrb's (the client thought there was no currently running session when in fact there was one).

Did anything in particular cause this error, or did you just receive it randomly? And what happened afterwards: was your bot able to continue running?

**Comment by jmfgdev** [comment]
>Did anything in particular cause this error, or did you just receive it randomly? And what happened afterwards: was your bot able to continue running?

I'd gladly provide more information. "my bot" is https://github.com/jmfgdev/amidabot-rb, for reference

The bot runs a very small set of functions, one of which is currently broken, but stable, if you know what I mean.

The bot runs fine after yes, for reference I was probably running ruby 2.4.0+ from rvm on CentOS 7
The bot is quite fast, and I sometimes recieve random errors like this, but the bot always continues executing.
