### ISSUE TITLE
The example for pm send shows sending a pm in relation to a command being run, I'm looking to send a pm unrelated to user input

### ISSUE THREAD

**Issue by jmfgdev** [meew0/discordrb#399]
I'm trying to incorporate the whenever gem into my bot, to add simple scripting of messages to me for diagnostics... But the example and the docs are not clear enough for me to implement the functionality.

This is what my code looks like right now, I just need to know what the equivalent to event.user.pm would be unrelated to an event, and how the syntax for that would look.

```
every 30.minutes do

end
```

Any help is welcome, my bot is totally free and I'm not doing this for personal gain or anything, I just want to learn.

**Comment by VxJasonxV** [comment]
`bot.pm([user_id], [message])`

**Comment by VxJasonxV** [comment]
`bot.user([user_id]).pm([message])`
http://www.rubydoc.info/gems/discordrb/Discordrb/User:pm

**Comment by z64** [comment]
Hi @jmfgdev !

While questions as issues are fine, it would be preferred if you could [join us on the Discord API server](https://discord.gg/0SBTUU1wZTWfFQL2).

As @VxJasonxV said, `Bot#user(id)` is one way to get a `User` object that you can `#pm` a message. There are other ways to get `User` objects but it depends on what you want to accomplish exactly.

**Comment by jmfgdev** [comment]
@VxJasonxV Thank you very much & @z64 Gotcha, I'll join up.

Thanks for the help everyone, I'll close this and ask in the future on Discord API
