### ISSUE TITLE
RubyDoc [View on GitHub] is not working.

### ISSUE THREAD

**Issue by kodbilenadam** [meew0/discordrb#417]
Due to changes on the repo. RubyDoc seems to failing on all [View on GitHub] links. 
Example:

http://www.rubydoc.info/github/meew0/discordrb/Discordrb/EmbedAuthor#embed-instance_method

![image](https://user-images.githubusercontent.com/7461799/30936940-10adfc84-a3de-11e7-9da7-711286142440.png)

When you click any [View on GitHub] link it's always showing a 404 error page instead of the source.

**Broken Page:**
https://github.com/meew0/discordrb/blob/Discordrb/lib/discordrb/data.rb#L1990
**Proper Page:**
https://github.com/meew0/discordrb/blob/master/lib/discordrb/data.rb#L1990

**Comment by z64** [comment]
I believe this is an issue with RubyDoc / YARD. Perhaps there might be some configuration setting we're missing, but I've been meaning to investigate exactly why anyway, so I'll keep this open as a reminder to report my findings.

**Comment by z64** [comment]
It would indeed appear this is an upstream "problem" with docs generation, quite a stale one.

See:
- "Fixes GitHub links" https://github.com/docmeta/rubydoc.info/pull/103
- "'View Source' links to Github not working on many repos" https://github.com/docmeta/rubydoc.info/issues/91

The GitHub URLs work if you use: http://www.rubydoc.info/github/meew0/discordrb/master (note `master` on the end here)

If you just go to http://www.rubydoc.info/github/meew0/discordrb, the branch name cannot be inferred, which is used to build the permalink.
