### ISSUE TITLE
Error while connecting to the websocket

### ISSUE THREAD

**Issue by pippognetow** [meew0/discordrb#418]
[ERROR : websocket @ 2017-09-29 16:51:27.325] An error occurred while connecting to the websocket!
[ERROR : websocket @ 2017-09-29 16:51:27.325] Exception: #<Discordrb::Errors::NoPermission: The bot doesn't have the required permission to do this!>
[ERROR : websocket @ 2017-09-29 16:51:27.325] /usr/local/rvm/gems/ruby-2.3.4/gems/discordrb-3.2.1/lib/discordrb/api.rb:68:in `rescue in raw_request'
[ERROR : websocket @ 2017-09-29 16:51:27.325] /usr/local/rvm/gems/ruby-2.3.4/gems/discordrb-3.2.1/lib/discordrb/api.rb:66:in `raw_request'
[ERROR : websocket @ 2017-09-29 16:51:27.325] /usr/local/rvm/gems/ruby-2.3.4/gems/discordrb-3.2.1/lib/discordrb/api.rb:92:in `request'
[ERROR : websocket @ 2017-09-29 16:51:27.325] /usr/local/rvm/gems/ruby-2.3.4/gems/discordrb-3.2.1/lib/discordrb/api.rb:227:in `gateway'
[ERROR : websocket @ 2017-09-29 16:51:27.325] /usr/local/rvm/gems/ruby-2.3.4/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:490:in `find_gateway'
[ERROR : websocket @ 2017-09-29 16:51:27.325] /usr/local/rvm/gems/ruby-2.3.4/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:495:in `process_gateway'
[ERROR : websocket @ 2017-09-29 16:51:27.325] /usr/local/rvm/gems/ruby-2.3.4/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:508:in `connect'
[ERROR : websocket @ 2017-09-29 16:51:27.325] /usr/local/rvm/gems/ruby-2.3.4/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:432:in `block in connect_loop'
[ERROR : websocket @ 2017-09-29 16:51:27.325] /usr/local/rvm/gems/ruby-2.3.4/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:431:in `loop'
[ERROR : websocket @ 2017-09-29 16:51:27.325] /usr/local/rvm/gems/ruby-2.3.4/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:431:in `connect_loop'
[ERROR : websocket @ 2017-09-29 16:51:27.325] /usr/local/rvm/gems/ruby-2.3.4/gems/discordrb-3.2.1/lib/discordrb/gateway.rb:161:in `block in run_async'

**Comment by z64** [comment]
Hi @pippognetow , 

Is this still an issue? If so, I'll need more information about how you are configuring your bot, and the conditions around when this exception occurred.

- Is this a Bot or a User token you are trying to connect with?
-  If a User token, are you passing `type: :user` to `Bot.new`? A sample of your `Bot.new` line would be great.
- Does this occur upon first startup, or sporadically throughout the bot processes lifecycle, like on a resume from a websocket crash / disconnect, or when doing some other specific action?

You're welcome to join us on the [Discord API server](https://discord.gg/0SBTUU1wZTWfFQL2) and we may be able to more quickly work with you to diagnose your issue. In any case, we'll do our best to help you.

**Comment by z64** [comment]
Closing this for now @pippognetow . Please feel free to comment back or reopen if you are still experiencing issues connecting and have some more details, per my last comment. For more immediate support for general troubleshooting / questions, please feel free to [join us on the Discord API server](https://discord.gg/0SBTUU1wZTWfFQL2) as well.
