### ISSUE TITLE
Error installing discordrb

### ISSUE THREAD

**Issue by Sonrio224** [meew0/discordrb#42]
got this error when trying to install this on linux mint. 

ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in "require": cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in "require"
	from extconf.rb:2:in <main>

any ideas on how to fix?

**Comment by meew0** [comment]
Try updating Ruby, discordrb only supports 2.1.0 and above.

**Comment by Sonrio224** [comment]
I upgraded and got the same error. i assume you upgrade ruby by typing 'apt-get upgrade ruby' right?

**Comment by Sonrio224** [comment]
never mind. i updated from source and got it working.

Thanks :)
