### ISSUE TITLE
Document discordrb-webhooks in README

### ISSUE THREAD

**Issue by z64** [meew0/discordrb#441]
`discordrb-webhooks.gemspec` is easy to miss, and some might not understand what it's for. We should mention this other gem in the README so its more likely that people who only want a webhook client can find out about this.

It also has "separate" documentation that we should link as well:
http://www.rubydoc.info/gems/discordrb-webhooks

Since, because of how docs generation works, only the docs for `discordrb` are shown on http://www.rubydoc.info/gems/discordrb unless you're looking at the github docs.

**Comment by AnanaGame** [comment]
This issue could be closed perhaps?

**Comment by z64** [comment]
#460 isn't merged yet
