### ISSUE TITLE
Explicitly enable private/direct messages

### ISSUE THREAD

**Issue by mtjhax** [meew0/discordrb#442]
Just an idea -- it would be helpful to be able to explicitly configure if a bot/command will respond to DMs.

As far as I can tell, the only practical way to accept DMs right now is to leave the list of channels unrestricted, but this will have the bot responding on every channel which is not necessarily desirable.

Ideally a bot/command could be configured to:
- Accept DMs and messages on any channel
- Accept DMs and messages on a list of channels
- Ignore DMs and accept messages on any channel
- Ignore DMs and accept messages on a list of channels
- Only accept DMs (maybe with option `channels: false`?)

I would implement this as an option `private_channels: [true, false]`. I could probably find time to contribute a PR if this idea seems useful to others.

**Comment by LikeLakers2** [comment]
Not against the idea of having it as a switch when making the command, but I'd like to point out that you can do all of what you suggested with a single line of code in commands where it's needed. See [here](https://gist.github.com/LikeLakers2/6ccef03d65ab6d76cae0fdc0183f487f#file-solutions-md).

**Comment by z64** [comment]
Hi @mtjhax,

Thanks for opening this discussion, and thanks @LikeLakers2 for the examples. And sorry for the delay, I've been on vacation :snowflake: :tada: 

While I agree on the use cases, such an addition doesn't fit with the state of this project *right now*.
- The [3.3 milestone](https://github.com/meew0/discordrb/milestone/15) represents our current feature freeze.
- #390 represents the first steps we'd like to take towards 4.0
- Not explicitly detailed here, a lot of our active community members have a strong desire to greatly improve our spec suite. This, in my opinion, is where we need the most help. Asserting the libraries current behavior will allow us to more effortlessly refactor components (*and add new ones like your suggestion*) with less frustration about things being broken, and give greater piece of mind to our users.

Personally, I'm pretty critical of our current event attribute matching system. I feel that a lot of it could be simplified and made more powerful with some metaprogramming and driven by user given lambdas (`proc`, etc.) to match events on *any* arbitrary condition, be it on data object properties or SQL queries, and not just the "predefined" ones that the current event system provides. This is really big picture rambling, though.

All that said - if you would like to make a PR, please feel free. Myself and others happy to review it, though I can't say when it would be merged (especially without specs, if that isn't something you're comfortable with - which isn't the end of the world). I think the event matching system is unlikely to see major conflicting change with such a PR over the course of 3.3 -> 4.0.

And fully on topic, this should really be done by matching on [channel type](http://www.rubydoc.info/gems/discordrb/Discordrb%2FChannel:type). We deviate from the language of the API in a lot of places, sometimes to the libraries detriment in my opinion when trying to figure out how our abstractions work. Matching our UI with Discord's object properties in this case is less abstract but still understandable, so I don't think `private_channels` as a bool is desirable:
```rb
bot.message(channel_types: [:server, :private]) do |event|
  # Handle guild and DMs here
end

bot.message(channel_types: [:private]) do |event|
  # Handle only DMs here
end
```
Or something similar. Matching on specific channels can already be done with the [`in` attribute](http://www.rubydoc.info/gems/discordrb/Discordrb/EventContainer#message-instance_method), although it doesn't accept arrays at quick glance, though [commands do](http://www.rubydoc.info/gems/discordrb/Discordrb%2FCommands%2FCommandContainer:command).

Any questions, feel free to reply here or [join us on Discord](https://discord.gg/cyK3Hjm).

**Comment by z64** [comment]
Similar to #428, I don't see us tacking on further features to CommandBot until its feature set and function as a whole is put on the table and discussed. Features like #498 in the interim really lend itself to enabling arbitrary filtering like this. Thanks for opening, and hopefully the CommandBot will be in a more flexible state in the future.
