### ISSUE TITLE
Link to Documentation in Wiki is outdated

### ISSUE THREAD

**Issue by Snackomat** [meew0/discordrb#458]
Link to Documentation in Wiki is outdated. Please update it to [the newer one](http://www.rubydoc.info/github/meew0/discordrb/). Or is it intended that the one you are linking to is not completed and outdated?

**Comment by Snackomat** [comment]
Same goes for the link in the #ruby-discordrb channel in Discord

**Comment by z64** [comment]
I've fixed the invite in the wiki, thanks.

Both of those documentation links are valid, but `gems` should be preferred.

**Comment by IvoPereira** [comment]
@z64 invite link seems to be expired again.

**Comment by z64** [comment]
@IvoPereira The invite `cyK3Hjm` is still registered and working. What are you referring to?
