### ISSUE TITLE
The API appears to be caching user properties and not updating them

### ISSUE THREAD

**Issue by kirillian** [meew0/discordrb#46]
We're currently investigating this, but it appears that the api caches user properties (such as username/name) and when the user updates this, the normal discord clients see the change, but the bot is not recognizing a change...mentions still work fine because they reference the user's id (e.g. user.mention returns ```<@83540519413616640>``` instead of ```kirillian``` which, understandably enables the clients and bot to both correctly identify me, but the name isn't being updated. More investigation forthcoming.

**Comment by meew0** [comment]
I've encountered this problem in one of my bots too. It should be an easy fix though, just overwrite the user properties in the `USER_UPDATE` event
