### ISSUE TITLE
API::Server.add_emoji out of date, missing abstractions

### ISSUE THREAD

**Issue by VxJasonxV** [meew0/discordrb#470]
We discovered in #discordrb today that emoji_add for a server now requires a [roles whitelist parameter](https://discordapp.com/developers/docs/resources/emoji#create-guild-emoji). As of this writing, [current git master](https://github.com/meew0/discordrb/blob/6a0e4cade133fe63ec049fa163d89ee3a71e8436/lib/discordrb/api/server.rb#L440-L452) does not support this.

**Comment by z64** [comment]
Yep. As discussed, it's missing but not required.

We also don't have abstractions for managing emoji. Especially considering that these endpoints are now no longer restricted to user accounts, we should add them.
