### ISSUE TITLE
Honestly, Just Use Crystal Instead

### ISSUE THREAD

**Issue by z64** [meew0/discordrb#475]
You guys probably all know by now, but there's a chance that there's some people on GitHub who I can't spread the Good Word to, so here it is.

# Why not Ruby?

- **Dynamic typing.** You have no idea what it's going to type next! I once left my computer alone with a Ruby project open, and it started typing the entire body of work from Shakespeare. I was so embarassed that someone might have gotten the idea that I was well-read and cultured.

- **It isn't even blazing fast, doesn't prevent segfaults, or guarantee thread safety.** Where are your threads the last time you checked? Do you even know? What kind of parent process are you? They could be out getting segfaulted right now. And where are you? Right here, too slow to protect them because you aren't blazingly fast. Just "fast enough". Let that sink in.

- **Gee, Bill!**
![image](https://user-images.githubusercontent.com/6119032/38170477-81abd91c-3554-11e8-8286-cf4ce9c1297e.png)

# Have you heard of our Lord and Savior, Crystal?

- **Static typing.** Never be afraid to bring your ThinkPad to Starbucks again and have your buffers go rogue while you pick up your latte, because the creators of Crystal don't even like Shakespeare. Static typing also has that effect of wearing nice wool socks and rubbing them on the carpet - surprise your friends and coworkers when you electrocute them, and develop an irrational fear of metal doorknobs!

- **It's basically C 2.0.** No one writes C anymore, because it's kind of like someone started to write "Crystal", but couldn't figure out the last 6 letters. But the creators of Crystal figured that out, and now it's great, so much better than "C" (`1 > 7`). And don't worry about keeping your threads safe - Crystal doesn't even have threads!

- **Null reference checks, Bill!**
![image](https://user-images.githubusercontent.com/6119032/38170665-03a3f856-3559-11e8-8b2e-9502d14b0437.png)

# Ahhh, I get it now, I'm like, totally convinced.

Thanks!

**Comment by PixeLInc** [comment]
Yeah, this is a good idea honestly.

**Comment by omnilord** [comment]
Seems legit.

**Comment by Deerskin** [comment]
Why go to Taco Bell when Chipotle is next door

**Comment by z64** [comment]
hi welcome to chilis

**Comment by z64** [comment]
Bah humbug! :) :heart:
