### ISSUE TITLE
Send a file to channel

### ISSUE THREAD

**Issue by abbasmaheryar** [meew0/discordrb#490]
Hello,

I have currently defined a variable to the CommandBot.new object. I want to send a file to a channel, but make it so that it sends it to the channel the user called the command from. The only way to to this is by using the Channel object. Is there a way I can integrate two objects to allow this in my code, or is there a work around?

**Comment by z64** [comment]
Hello!

First, please be sure to review our wiki, particularly: https://github.com/meew0/discordrb/wiki/Commands

The important takeaways from this, is when you create commands, they are yielded an `event` which has contextual information:

```rb
bot.command(:foo) do |event|
  event.user #=> User object that ran this command
  event.channel #=> Channel object where this command was run
end
```

Specifically, `event` in this case is a `CommandEvent`, which you can find an exhaustive list of methods here: https://www.rubydoc.info/gems/discordrb/Discordrb/Commands/CommandEvent

From there of course, you can send a file:
```rb
event.channel.send_file(File.open('path_to_file.jpg', 'r'))
```

For future questions, our issue tracker is fine, but for quicker responses where we can more easily work with you, please consider joining us [on Discord](https://discord.gg/cyK3Hjm).

**Comment by z64** [comment]
Pretty certain I've answered your question here. If you need further help, feel free to comment back here, or ask on Discord.
