### ISSUE TITLE
Malformed Event Spec

### ISSUE THREAD

**Issue by Daniel-Worrall** [meew0/discordrb#492]
https://github.com/meew0/discordrb/blob/master/spec/event_spec.rb#L141

Blame the spanner

(This should be describe)

**Comment by Daniel-Worrall** [comment]
This is a further issue than I thought. We should restructure our specs to properly adhere to a standard.

It's a bigger issue than just changing module to describe and I'll revisit this later when I do testing on how Rspec likes multi-level modules

**Comment by z64** [comment]
Can we consider this a dupe of #259 and close? Or, otherwise drill this issue down into something more specific that can be actioned on?
