### ISSUE TITLE
Deleting a server should be more difficult

### ISSUE THREAD

**Issue by connorshea** [meew0/discordrb#510]
There should probably be a way to prevent the user from shooting themselves in the foot. 🤷‍♂️ 

https://github.com/meew0/discordrb/blob/276e2afd5f16bde804d0794d57cfdfe4c6041180/lib/discordrb/data.rb#L3318-L3321

i.e. rename the method to `delete!` and have `delete` just print a message that directs the user to `delete!`?

**Comment by z64** [comment]
I more or less have to disagree with this.

- Bots cannot delete servers they do not own. The use case or need for bots to create servers is extremely rare, and to create more than 10 you need to be whitelisted.
- Selfbots can't delete servers they do not own. Selfbot code will be deprecated and removed someday.
- This will fail as a selfbot with an account that has 2FA
- There are other irreversible actions that could be considered "dangerous" that aren't practical to warn against
- A method that does nothing isn't a solution

**Comment by connorshea** [comment]
I forgot servers can only deleted by owners. Disregard my stupidity 🙇
