### ISSUE TITLE
It is impossible to find a role by id

### ISSUE THREAD

**Issue by shadowtftby** [meew0/discordrb#537]
[93] pry(main)> bot.server(326059319261134848).roles.include?(489128822424207381)
=> true
[94] pry(main)> bot.server(326059319261134848).role(489128822424207381)
NoMethodError: undefined method `id' for {:name=>"new test role"}:Hash
from /home/shad/.rvm/gems/ruby-2.5.1/gems/discordrb-3.2.1/lib/discordrb/data.rb:2285:in `block in role'

**Comment by z64** [comment]
Sorry, this error makes no sense. It isn't possible - based on the little information you gave - for `@roles` inside of a `Server` instance to be `Array<Hash>`.

Not to mention, that hash is missing tons of information that should be in a role object, which is highly suspect. (This is completely disregarding that that hash would fail the `Role` constructor entirely fail, raising all kinds of exceptions)

Please provide more details about this code and your environment / a reproducible case.

**Comment by z64** [comment]
Please feel free to reopen this if you have more information, and we'll be happy to help diagnose what went wrong 🙂 

There's nothing that can be done with the provided info that could only suggest misuse of our internal API in some way (`Server#add_role`? ..I can only guess..)
