### ISSUE TITLE
Wrong roles count after create new role

### ISSUE THREAD

**Issue by alex-saratovcev** [meew0/discordrb#541]
Hi!
After the new role is created server.roles return wrong count.
After 
https://github.com/meew0/discordrb/blob/384158618352f1a9af69ee595720b3ee88f01dab/lib/discordrb/data.rb#L3280

@roles array already have new role, and then we put duplicate role in array @roles on line:

https://github.com/meew0/discordrb/blob/384158618352f1a9af69ee595720b3ee88f01dab/lib/discordrb/data.rb#L3283

**Comment by z64** [comment]
Hi, thank you for reporting! Indeed, the role is cached twice when we receive the event from Discord later.

This is fixed with #488 which adjusts our caching logic.
