### ISSUE TITLE
Issues sending messages when not directly responding to an event

### ISSUE THREAD

**Issue by piotrb** [meew0/discordrb#57]
Hi,

So I'm having a bit of an issue sending messages .. 

I receive a message, and hold on to the `event.channel.id` .. then at a later time try to send a message via `@bot.send_message(that_channel_id, "bla bla")` .. but end up with a 404 Resource not found in the send_message code .. 

Any ideas what I might be doing wrong?

This seems to be the same between private messages and channel messages.

**Comment by piotrb** [comment]
I'm tingering with making a lita adapter (lita.io) using this gem, so I'm not using the standard bot loop as shown in the examples. I basically start the `Discordrb::Bot` and then issue commands to it from another context (I believe Lita uses EventMachine).

**Comment by meew0** [comment]
As I understand it, this was resolved in Discord.

**Comment by piotrb** [comment]
Yes, sorry, forgot about this issue being open.
