### ISSUE TITLE
Permissions do not take role position into account

### ISSUE THREAD

**Issue by omnilord** [meew0/discordrb#607]
# Summary
My bot has 2 roles:
- Role1 is at position 11
- Role2 is at position 4.

Role2 has manage messages allowed for the server.
Role1 has manage messages denied on a channel.

The following code incorrectly returns `true` for the channel where the bot is denied this permission.
```Ruby
bot_profile = Bot::BOT.profile.on(event.server)
bot_profile.permission?(:manage_messages, event.channel)
```

The error I am receiving is:
```
[ERROR : ct-3 @ 2019-03-09 02:24:41.525] Exception: #<Discordrb::Errors::NoPermission: The bot doesn't have the required permission to do this!>
[ERROR : ct-3 @ 2019-03-09 02:24:41.525] vendor/bundle/ruby/2.6.0/gems/discordrb-3.3.0/lib/discordrb/api.rb:86:in `rescue in raw_request'
[ERROR : ct-3 @ 2019-03-09 02:24:41.525] vendor/bundle/ruby/2.6.0/gems/discordrb-3.3.0/lib/discordrb/api.rb:80:in `raw_request'
[ERROR : ct-3 @ 2019-03-09 02:24:41.525] vendor/bundle/ruby/2.6.0/gems/discordrb-3.3.0/lib/discordrb/api.rb:112:in `request'
[ERROR : ct-3 @ 2019-03-09 02:24:41.525] vendor/bundle/ruby/2.6.0/gems/discordrb-3.3.0/lib/discordrb/api/channel.rb:121:in `delete_message'
[ERROR : ct-3 @ 2019-03-09 02:24:41.525] vendor/bundle/ruby/2.6.0/gems/discordrb-3.3.0/lib/discordrb/data.rb:2531:in `delete'
[ERROR : ct-3 @ 2019-03-09 02:24:41.525] src/commands/roll.rb:108:in `block (2 levels) in <module:Roll>'
[ERROR : ct-3 @ 2019-03-09 02:24:41.526] src/macros.rb:101:in `permissioned_eval'
[ERROR : ct-3 @ 2019-03-09 02:24:41.526] src/commands/roll.rb:108:in `block in <module:Roll>'
[ERROR : ct-3 @ 2019-03-09 02:24:41.526] vendor/bundle/ruby/2.6.0/gems/discordrb-3.3.0/lib/discordrb/commands/parser.rb:110:in `call'
[ERROR : ct-3 @ 2019-03-09 02:24:41.526] vendor/bundle/ruby/2.6.0/gems/discordrb-3.3.0/lib/discordrb/commands/command_bot.rb:226:in `execute_command'
[ERROR : ct-3 @ 2019-03-09 02:24:41.526] vendor/bundle/ruby/2.6.0/gems/discordrb-3.3.0/lib/discordrb/commands/command_bot.rb:323:in `simple_execute'
[ERROR : ct-3 @ 2019-03-09 02:24:41.526] vendor/bundle/ruby/2.6.0/gems/discordrb-3.3.0/lib/discordrb/commands/command_bot.rb:475:in `block in execute_chain'
```

src/commands/roll.rb, line 108:
```ruby
Bot.permissioned_eval(event, :manage_messages) { event.message.delete }
```

Bot.permissioned_eval:
```Ruby
class Bot
  def self.permissioned_eval(event, *permissions)
    return unless block_given?

    bot_profile = Bot::BOT.profile.on(event.server)
    permissions.each do |permission|
      return unless bot_profile.permission?(permission, event.channel)
    end

    yield
  end
end
```

At [Permissions.rb#L187](https://github.com/meew0/discordrb/blob/master/lib/discordrb/permissions.rb#L187) in master, it appears to fix the problem if you add a sort to the roles:
```
roles_to_check.sort { |a, b| a.position <=> b.position }.reduce(false) do |can_act, role|
```

Once fixed, what are the odds of having this fix backported to the 3.3 gem version?

---

## Environment
**Ruby version:**
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]

**Discordrb version:**
./vendor/bundle/ruby/2.6.0/gems/discordrb-3.3.0

**Comment by z64** [comment]
@omnilord I added a failing spec for 3.3 in #609 based on your description. Feel free to leave your :heavy_check_mark: .

I'm not sure about backporting. Not something we've done in the past (or that I've done myself in any project :slightly_smiling_face:)

I'm considering a point release soon though to get some of the recent features out.

**Comment by omnilord** [comment]
✔️Looks nice.

If by "point release" you mean 3.3.1, I think we're on the same page.  My point of view is that most of the recent changes in master seem to be aiming for the 4.0 release.  I wasn't sure if you'd want to include those changes in a 3.3.x version, is where I was coming from.

**Comment by z64** [comment]
Yeah, probably. And, I haven't actually milestoned anything that has been merged yet because I wasn't sure what our next release would be :slightly_smiling_face: We'll probably have a discussion about it sometime soon.
