### ISSUE TITLE
Triggering events from `raw`

### ISSUE THREAD

**Issue by mkaito** [meew0/discordrb#613]
What I'm looking to do is [this](https://discordjs.guide/popular-topics/reactions.html#listening-for-reactions-on-old-messages) from the discord.js documentation. I want the bot to get events for reactions on very old messages. How would I do that with discordrb?

Thanks!

**Comment by Daniel-Worrall** [comment]
http://meew0.github.io/discordrb/master/Discordrb/EventContainer.html#raw-instance_method

**Comment by z64** [comment]
discordrb does not have a message cache. All events will be emitted as they are received regardless of the messages age, or anything like that; you do not need to use a "raw" handler, and you can just use `Bot#reaction_add` (`EventContainer#reaction_add`) as normal

http://meew0.github.io/discordrb/master/Discordrb/EventContainer.html#reaction_add-instance_method
