### ISSUE TITLE
Bot.new: Base64.decode64(password) does not work as parameter

### ISSUE THREAD

**Issue by avengerx** [meew0/discordrb#62]
Hello,

This is more like a newbie question than a problem itself.

Thing is, if I try to use base64 decode method (just to not leave the password in the wide open), it fails!..

I can log if I do something like:
`bot = Discordrb::Bot.new 'my@email.address', 'my_passsword'`

But if I do:
```
require 'base64'
password = 'bXlfcGFzc3N3b3JkCg=='
bot = Discordrb::Bot.new 'my@email.address', Base64.decode64(password)
```

It does not work. :( Am I doing something really really obviously wrong? Shouldn't the constructor parameter passed be the decoded string at all?

Error when using base64 is just:
`[ERROR : main @ 2016-03-19 16:24:51.815] Exception: 400 Bad Request: {"password": ["Password does not match."]}`

So it is as if it didn't really resolve the function output at all!

**Comment by meew0** [comment]
That error means that the password you decoded is wrong, can you print out the decoded base64 before logging in and see if it really matches? (Also, why exactly are you using base64 for passwords? It provides no additional security)

**Comment by fabriciomurta** [comment]
Actually... hahah I've encoded the password with a line feed in the end! (\n)!

I had to `echo -n "my_password" | base64` instead. :P

**Comment by avengerx** [comment]
Actually... hahah I've encoded the password with a line feed in the end! (\n)!

I had to echo -n "my_password" | base64 instead. :P

I have indeed echoed the password over and over but somehow the extra line feed was not clear... maybe ruby trimmed it both in `puts` and `debug()`.
