### ISSUE TITLE
Bot.reaction_add and Bot.reaction_remove - undefined method

### ISSUE THREAD

**Issue by strelokhalfer** [meew0/discordrb#657]
# Summary

### How to reproduce:

1. Use `Bot.reaction_add` or `Bot.reaction_remove` event
2. Try to orbitain who reacted: `event.user`
3. Get this: 

> [ERROR : et-3 @ 2019-09-19 16:31:35.771] Exception: #<NoMethodError: undefined method 'server' for nil:NilClass>
> [ERROR : et-3 @ 2019-09-19 16:31:35.771] /home/strelokhalfer/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/bundler/gems/discordrb-07915cd1a668/lib/discordrb/events/reactions.rb:45:in 'server'
> [ERROR : et-3 @ 2019-09-19 16:31:35.771] /home/strelokhalfer/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/bundler/gems/discordrb-07915cd1a668/lib/discordrb/events/reactions.rb:26:in 'user'
> [ERROR : et-3 @ 2019-09-19 16:31:35.771] ./bot.rb:46:in 'block in <main>'
> [ERROR : et-3 @ 2019-09-19 16:31:35.771] /home/strelokhalfer/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/bundler/gems/discordrb-07915cd1a668/lib/discordrb/events/generic.rb:98:in 'call'
> [ERROR : et-3 @ 2019-09-19 16:31:35.771] /home/strelokhalfer/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/bundler/gems/discordrb-07915cd1a668/lib/discordrb/bot.rb:1250:in 'block in call_event'

### Possible fix:
replace `@server ||= @channel.server` with `@server ||= channel.server` in
>     def server
>       @server ||= @channel.server
>     end

## Environment

**Ruby version:**
ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-linux]

**Discordrb version:**
discordrb-07915cd1a668

**Comment by swarley** [comment]
This appears to have been fixed with #484

**Comment by z64** [comment]
Yes, `discordrb-07915cd1a668` is from 2018-02-05. Pretty certain that should fix it, so I'll close this for now. Please reopen with further details if there is still an issue. Thanks!
