### ISSUE TITLE
How to test if user has role "abc"

### ISSUE THREAD

**Issue by RWSDev** [meew0/discordrb#658]
I have a number of roles on my server and would like to be able to have the bot only allow certain commands if bot.event.user.role? "abc" ... I may not be understanding the implementation and quite possible doing this wrong.  

Any guidance would be much appreciated ... TIA

**Comment by Chew** [comment]
Hey! Glad you're here.

To answer your question, you're on the right track. First, find a role named "abc" (via `event.server.roles.find_by { |role| role.name == "abc" }`) which returns a role, then just do event.user.role? ^ response.

If you need more help, please join the official server and ask us there. https://discord.gg/discord-api we're in #ruby-discordrb

**Comment by Daniel-Worrall** [comment]
Adding to this, role names are not unique, so you may want to use role ids to distinguish them with `Role#id`.

**Comment by RWSDev** [comment]
Thank you both for the guidance.  I have it working now!
