### ISSUE TITLE
Voice Channel things will not work on Windows due to underlying library

### ISSUE THREAD

**Issue by kirillian** [meew0/discordrb#68]
The opus-ruby gem appears to really only be tested against Linux libraries...It's a wrapper around FFI which loads the opus library, but the gem itself doesn't account for the differences between FFI's API for linux library loading and Windows library loading. See:
https://github.com/mattvperry/opus-ruby/blob/master/lib/opus-ruby.rb
https://github.com/ffi/ffi/wiki/Basic-Usage#hello-windows-using-ffi

I think replacing or extending this gem will be mandatory to support Windows clients

**Comment by meew0** [comment]
I've been able to get voice to run on Windows flawlessly - if there's some problem with opus-ruby it must only occur for some people. Was there a specific problem somebody had?

**Comment by WhiskyWiskian** [comment]
Been getting this error when I connect my bot to a voice channel:

Exception: #<LoadError: Opus unavailable - voice not supported! Please install opus for voice support to work.>

**Comment by WhiskyWiskian** [comment]
I get this error when I connect my bot to a voice channel in Windows

Exception: #<LoadError: Opus unavailable - voice not supported! Please install opus for voice support to work.>

**Comment by WhiskyWiskian** [comment]
I get this error when I connect my bot to a voice channel in Windows

Exception: # <LoadError: Opus unavailable - voice not supported! Please install opus for voice support to work.>

**Comment by WhiskyWiskian** [comment]
I get this error when I connect my bot to a voice channel in Windows

Exception: (#)<LoadError: Opus unavailable - voice not supported! Please install opus for voice support to work.>

**Comment by kirillian** [comment]
Try using preview to view what will be posted.

**Comment by WhiskyWiskian** [comment]
I get this error when I connect my bot to a voice channel in Windows

`Exception: #<LoadError: Opus unavailable - voice not supported! Please install opus for voice support to work.>`

**Comment by kirillian** [comment]
@WhiskyWiskian can you demonstrate that you have opus installed? I.E. show path information etc...

**Comment by WhiskyWiskian** [comment]
C:\Ruby22\lib\ruby\gems\2.2.0\gems\opus-ruby-1.0.1

**Comment by meew0** [comment]
Not opus-ruby, but opus itself

**Comment by WhiskyWiskian** [comment]
Had a problem with that, I'm not sure how to install opus. I have the files ready but don't know what to do with it, not sure if I should link it to Windows or paste the dlls to a specific folder. Had a small conversation about this on the server, I'll backtrack the messages and send it to you. (the conversation explained the situation well)

**Comment by meew0** [comment]
You need the `libopus-0.dll` anywhere the bot can find it, either somewhere in your PATH or in the directory the bot is running from.

**Comment by WhiskyWiskian** [comment]
Do I make a new Path at environment variables and link it to where libopus-0.dll is? libopus-0.dll is already at the directory where my bot is running from, must I have a code to link it up like libsodium?

**Comment by meew0** [comment]
You shouldn't have to - it should work as is if it's in the directory your bot is running from. Can you try renaming it to `opus.dll`?

**Comment by WhiskyWiskian** [comment]
Renaming it to opus.dll works, thanks

**Comment by meew0** [comment]
Ah, good, I'll keep this in mind and write it into the requirements.

**Comment by djlazz3** [comment]
thx this helped a lot
