### ISSUE TITLE
Allow find_channel handle "#channel" matching

### ISSUE THREAD

**Issue by avengerx** [meew0/discordrb#71]
Currently [find_channel](https://github.com/meew0/discordrb/blob/master/lib/discordrb/bot.rb#L331) finds channels (on the specified server or on all present servers) by matching its full name.

In discord, it is common to see channels prefixed by a sharp symbol (#). So it would be more intuitive for the search to handle this character.

But there's something I didn't try yet: can a channel have a sharp symbol on its name? For example, is it possible to have a discord "##general"? (while internal name would be "#general")

![chandigital](https://cloud.githubusercontent.com/assets/808610/14020177/c3b7897c-f1b4-11e5-87fc-07c6f41cae6f.png)

Not possible. Then, it is enough just, if the first character in the search is a "#", then strip it from the searched string! :) Tad easy, I think. :)

**Comment by meew0** [comment]
Discord channels can't have that symbol in their name, so we can just strip it from the `find_channel` argument if it's present and continue as normal

**Comment by meew0** [comment]
I've looked at this and realized that voice channels can have the symbol in their name, so this won't work because stripping the # will not allow voice channels with that name to be found.
