### ISSUE TITLE
Spaces after prefix still allow calling a command (eg. "!   ping")

### ISSUE THREAD

**Issue by green-big-frog** [meew0/discordrb#76]
`!   ping` still triggers `!ping`

This is unwanted behavior from my POV.

**Comment by meew0** [comment]
Does this happen with advanced functionality off or on?

**Comment by green-big-frog** [comment]
Have only tested it with `advanced_functionality: false`

**Comment by meew0** [comment]
Fixed in that commit, since the behaviour may also be desirable I added a config option `:spaces_allowed` to re-enable it.

**Comment by green-big-frog** [comment]
Thanks
