### ISSUE TITLE
Full ignore at message receivment

### ISSUE THREAD

**Issue by green-big-frog** [meew0/discordrb#78]
I'd like to have full ignoring implemented. The dropping of msg's should best happen right after they got received so that f.e. buckets don't get triggered.

`bot.ignore(id)`

(Automatic removal also would be nice `bot.ignore(user: id, time: 12h)` )

**Comment by meew0** [comment]
I probably won't do automatic removal as it requires running an entirely separate thread in the background, but a basic ignoring feature is feasible
