### ISSUE TITLE
Adding more server functions

### ISSUE THREAD

**Issue by SnazzyPine25** [meew0/discordrb#79]
You should add more server functions to help make it simpler to detect text/voice channels.
 
`Server.text_channels`
`Server.text_channel_count`
`Server.voice_channels`
`Server.voice_channel_count`

**Comment by meew0** [comment]
`text_channel_count` and `voice_channel_count` seems unnecessary since you can just run `count` on the other two attributes, but I'll take a look at those

**Comment by AnhNhan** [comment]
I would like to request `Server#online_users`, which may or may not take bot accounts (self / tagged) into account (maybe parameter?). Useful here and there, especially if I don't have to filter each time.

**Comment by meew0** [comment]
Also a good idea; can you open a separate issue so I don't lose track of it?

**Comment by SnazzyPine25** [comment]
also to note: for every `.` i really meant `#`
