### ISSUE TITLE
Add a server function

### ISSUE THREAD

**Issue by SnazzyPine25** [meew0/discordrb#81]
`Server#voice_channels ⇒ Hash<Integer => Array<User>`

Returns:
- `(Hash<Integer => Array<User>>)` — Users active in a voice channel, grouped by channel ID of voice channels.

**Comment by meew0** [comment]
What's wrong with calling the [`users`](http://www.rubydoc.info/gems/discordrb/2.0.0/Discordrb%2FChannel%3Ausers) method on the channel objects?

**Comment by SnazzyPine25** [comment]
Good point.
