### ISSUE TITLE
Add a new attribute to EventContainer#message

### ISSUE THREAD

**Issue by SnazzyPine25** [meew0/discordrb#84]
`EventContainer#message(attributes = {}) {|event| ... } ⇒ MessageEventHandler`

## **Options Hash (_attributes_):**
- **:message** (Message) — Exactly matches the message.

**Comment by meew0** [comment]
There's already `:content`, `:with_text`, and `:exact_text`, do we really need another one?

**Comment by SnazzyPine25** [comment]
I need my bot to delete messages. This seemed like a good resolution.

**Comment by meew0** [comment]
Well, all of these do exactly what you need, is there any particular reason you need another alias?

**Comment by SnazzyPine25** [comment]
It's not in the docs so i didn't think is outputs a message object

**Comment by meew0** [comment]
`:content` is in there: http://www.rubydoc.info/gems/discordrb/2.0.1/Discordrb%2FEventContainer%3Amessage

**Comment by SnazzyPine25** [comment]
oh i didnt have the `2.0.1/` in the site. Nevermind.

**Comment by meew0** [comment]
It's in the previous versions too

**Comment by SnazzyPine25** [comment]
im confusing myself, sorry

**Comment by meew0** [comment]
I'll just close this
