### ISSUE TITLE
event.author Problem

### ISSUE THREAD

**Issue by SnazzyPine25** [meew0/discordrb#95]
So while I hooked this up to a event that triggers everytime a message is found, sometimes I get a error that says that author is nil.

```
[ERROR : et-15 @ 2016-04-13 09:00:27.052] Exception: #<NoMethodError: undefined method `id' for nil:NilClass>
[ERROR : et-15 @ 2016-04-13 09:00:27.055] shush.rb:160:in `block in <module:FilterEdit>'
[ERROR : et-15 @ 2016-04-13 09:00:27.058] /home/snazzah/.rvm/gems/ruby-2.3.0/gems/discordrb-2.0.2/lib/discordrb/events/generic.rb:82:in `call'
[ERROR : et-15 @ 2016-04-13 09:00:27.059] /home/snazzah/.rvm/gems/ruby-2.3.0/gems/discordrb-2.0.2/lib/discordrb/bot.rb:1362:in `block in call_event'
```

`ind = wid.index(event.author.id.to_s)`
ind being a array of user ids as a string.

**Comment by meew0** [comment]
Can you show the rest of the code?

**Comment by SnazzyPine25** [comment]
It's in a event that activates everytime a message is sent.
not really sure why you need the rest.

**Comment by VxJasonxV** [comment]
Being able to copy/paste complete code and test it is a very nice thing.

**Comment by SnazzyPine25** [comment]
https://gist.github.com/SnazzyPine25/bd7198e3dc37be03359d7035aa922614
